--- 
- hosts: loadbalancer
  tasks:
      - name: package epel-release upgrade
        yum: name=epel-release
      - name: Firewall service https enable
        firewalld: service={{item}} permanent=true state=enabled
        with_items:
        - http
        - https
      - name: Firewall open ports
        firewalld: port={{item}} permanent=true state=enabled
        with_items:
        - 8080/tcp
        - 8443/tcp
      - name: nginx start
        yum: name=nginx state=present
      - name: Enable and start nginx
        service: enabled=true name=nginx state=started
